matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd MeetBackend/
      install:
        - npm install
      script:
        - npm run test
      after_success:
        - npm run coverage

notifications:
  email: false
