matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd MeetBackend/
      install:
        - npm install
      script:
        - NODE_ENV=test mocha --timeout 10000
      after_success:
        - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  email: false
