matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd MeetBackend/
      install:
        - npm install
      script:
        - npm run test
      after_success:
        - ./node_modules/.bin/mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false
